spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/regular
    username: bpaiva
    password: 2001
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update


  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  springdoc:
    api-docs:
      path=/api-docs:


  swagger-ui:
    path=/swagger-ui-custom:
      html: